name: NoStrippedLog
version: 1.1.1
author: dikahdoff
main: com.dikahdoff.nsl.NSL
api-version: 1.16
description: Disables the stripping of logs
commands:
  nsl:
    description: MainCommand
    usage: /<command>
    aliases: [nostrippedlog,nostrippedlogs]